# Generated by Django 2.2 on 2019-05-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_auto_20190503_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Автор(ы)'),
        ),
    ]
