# Generated by Django 2.2 on 2019-04-29 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название книги')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Обложка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('year', models.IntegerField(verbose_name='Год издания')),
                ('pages', models.IntegerField(verbose_name='Страниц')),
                ('binding', models.CharField(max_length=40, verbose_name='Переплет')),
                ('format', models.CharField(max_length=120, verbose_name='Формат')),
                ('isbn', models.CharField(max_length=40, verbose_name='ISBN')),
                ('weight', models.CharField(max_length=10, verbose_name='Вес')),
                ('age_limit', models.CharField(max_length=4, verbose_name='Возрастные ограничения')),
                ('sum', models.IntegerField(verbose_name='Количество книг в наличии')),
                ('active', models.BooleanField(default=True, verbose_name='Доступна для заказа')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Рейтинг')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('author', models.ManyToManyField(related_name='directory', to='directory.Author', verbose_name='Автор(ы)')),
                ('genre', models.ManyToManyField(related_name='directory', to='directory.Genre', verbose_name='Жанр(ы)')),
                ('publishing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.Publishing', verbose_name='Издательство')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.Series', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-name'],
            },
        ),
    ]
